### ISSUE TITLE
AV Detected!!!

### ISSUE THREAD

**Issue by mcuong223** [dekrypted/simple-cookie-stealer#10]
Built and ran the output file and a cookies file sent to the webhook
But the output.exe file was detected by Windows Defender!
Please help!

**Comment by Nitrozena** [comment]
Exclude the output.exe file from Windows Defender scanning:

Open Windows Security by clicking on the shield icon in the taskbar.
Go to "Virus & threat protection" and click on "Manage settings."
Scroll down to the "Exclusions" section and click on "Add or remove exclusions."
Click on "Add an exclusion" and select "File."
Navigate to the location where the output.exe file is located and select it.

**Comment by dekrypted** [comment]
Since so many people are using this, antivirus softwares are beginning to detect it. I won't be fixing this, as it's a relatively simple project and I don't feel like making it complicated. You can learn how to manually edit and compile the main.py file if you'd like, as this can help with detections. I'd advise learning more about programming before trying this though.
